name: CI
on:
  pull_request:
  push:
  release:
    types: [ published ]
jobs:
  ciJvms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Setup Scala-CLI
        uses: VirtusLab/scala-cli-setup@v1
        with:
          scala-cli-version: latest
      - run: scala-cli config power true
      - run: scala-cli publish local .

  ci:
    if: always()
    runs-on: ubuntu-latest
    needs: [ ciJvms ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
