name: CI
on:
  push:
  release:
    types: [ published ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true
    - name: Test
      run: scala-cli compile . --cross

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true
    - name: Publish
      run: scala-cli publish . --cross
      env:
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        PUBLISH_SECRET_KEY: ${{ secrets.PUBLISH_SECRET_KEY }}
        PUBLISH_SECRET_KEY_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
